backend:
  name: git-gateway
show_preview_links: true
display_url: https://tiery.com.br/
site_url: https://tiery.com.br/
media_folder: "src/assets/images"
public_folder: "assets/images"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Projects"
        name: "projects"
        fields:
          - label: "Projects"
            name: "projects"
            format: json
            widget: "list"
            extension: "json"
            create: true
            file: "src/_data/projects.json"
            fields:
              - {
                  label: "Layout",
                  name: "layout",
                  widget: "hidden",
                  default: "project",
                }
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Project Date",
                  name: "projectDate",
                  widget: "datetime",
                  dateFormat: "YYYY-MM-DD",
                  timeFormat: "HH:mm",
                  format: "YYYY-MM-DD HH:mm",
                }
              - { label: "Content", name: "description", widget: "markdown" }
              - {
                  label: "Tags",
                  name: "tags",
                  widget: "list",
                  default: ["dancer"],
                }
              - {
                  label: "Gallery",
                  name: "galleryImages",
                  widget: "list",
                  summary: "{{fields.image}}",
                  field: { label: Image, name: image, widget: image },
                }
      - label: "Settings"
        name: "settings"
        delete: false
        file: "src/_data/settings.json"
        extension: "json"
        format: json
        editor:
          preview: false
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - {
              label: "Contact CTA Title",
              name: "contact_cta_title",
              widget: "string",
              default: "don’t be shy, lets talk",
            }
          - {
              label: "Background Gradient",
              name: "bg_gradient",
              widget: "list",
              default: ["#d77e92", "#907ed7", "#7eccd7"],
            }
          - {
              label: "Opening Phrases",
              name: "opening_phrases",
              widget: "list",
              default:
                [
                  "artist",
                  "performer",
                  "motion-being",
                  "comunicate",
                  "to engage",
                ],
            }
          - {
              label: "Bio > Title",
              name: "bio_title",
              widget: "string",
              default: "Hey you,",
            }
