backend:
  name: git-gateway
show_preview_links: true
display_url: https://tiery.com.br/
site_url: https://tiery.com.br/
media_folder: "assets/images"
public_folder: "images"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: "projects"
    label: "Projects"
    create: true
    folder: "src/_data/projects"
    slug: "{{slug}}"
    extension: "json"
    format: json
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "string" }
      - {
          label: "Project Date",
          name: "projectDate",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "Publish Date",
          name: "publishDate",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Cover", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "categories"
    label: "Categories"
    create: true
    folder: "src/_data/categories"
    slug: "{{slug}}"
    extension: "json"
    format: json
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "category",
        }
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Name", name: "title", widget: "string" }
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "src/_data/settings.json"
        description: "General Site Settings"
        fields:
          - { label: "Global title", name: "site_title", widget: "string" }
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {
                  label: "Default Thumbnail",
                  name: thumb,
                  widget: image,
                  class: "thumb",
                  required: false,
                }
